# This file is used to override default values used by the Ant build system.
#
# This file must be checked into Version Control Systems, as it is
# integral to the build system of your project.

# This file is only used by the Ant script.

# You can use this to override default values such as
#  'source.dir' for the location of your java source folder and
#  'out.dir' for the location of your output folder.

# You can also use it define how the release builds are signed by declaring
# the following properties:
#  'key.store' for the location of your keystore and
#  'key.alias' for the name of the key to use.
# The password will be asked during the build when you use the 'release' target.

android.ndk=/Users/jouderian/android-ndk-r10c
android.platform=/Users/jouderian/Library/android-sdk-macosx/platforms/android-15
google.apis=/Users/jouderian/Library/android-sdk-macosx/add-ons/addon-google_apis-google-14
titanium.platform=/Users/jouderian/Library/Application Support/Titanium/mobilesdk/osx/3.4.0.GA/android